### ISSUE TITLE
[BUG] Never got any Config files while using Fabric 1.16.4/.5

### ISSUE THREAD

**Issue by miathegaymer** [ErdbeerbaerLP/DiscordRichPresence#24]
**What happened?**
Never got any Config files while using Fabric 1.16.4/.5

**What should happen?**
A Config file folder should have generated in my base .minecraft directory, but nothing happened.

**Steps to reproduce**
- Use Fabric 1.16.4 or 1.16.5
- Check .minecraft directory for config file folder
- Nothing's there...

**Version**
- [/ ] 1.16

Mod version 
2.0.7
**Config file**
- No config file generated...

**Crash report if available (use https://paste.dimdev.org or https://pastebin.com)**
-

**Additional info**

- I want to set up DRP to not show my server IP and to use my Discord apps Rich Presence setup, but I can't do that until this issue is resolved.

**Comment by ErdbeerbaerLP** [comment]
This mod is not available for fabric
