### ISSUE TITLE
Spammed logs

### ISSUE THREAD

**Issue by MelanX** [ErdbeerbaerLP/DiscordRichPresence#5]
Could you please remove these lines or add it to the config that you can turn off logging?
https://github.com/ErdbeerbaerLP/DiscordRichPresence/blob/1.15/src/main/java/de/erdbeerbaerlp/discordrpc/DRPCEventHandler.java#L208-L209
My whole log is full of these messages :D
This version: 2.0.3-1.15

**Comment by ErdbeerbaerLP** [comment]
Oh, this should actually log as debug not an info message. I will fix that soon
