### ISSUE TITLE
Can't connect to hypixel

### ISSUE THREAD

**Issue by Nacho4785** [ErdbeerbaerLP/DiscordRichPresence#6]
I can't connect to hypixel using the mod on Forge 1.15.2.
I get kicked to the limbo.

**Comment by ErdbeerbaerLP** [comment]
Update your forge version. It seems to be finally fixed in an newer version. Tested with Forge 31.2.5.

However, this mod can't parse the Hypixel game info right now (working on it right now)

**Comment by ErdbeerbaerLP** [comment]
Nvm somehow it worked once.
